# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
plugins: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Vølchøk
tagline:             'Notes'
description:         'Nonsense Notes'
url:                 https://v0lch0k.github.io/
baseurl:             https://v0lch0k.github.io/
paginate:            7

# About/contact
author:
  name:              Vølchøk
  url:               https://v0lch0k.github.io/
 # email:             

# Custom vars
version:             2.0

# Social Media
github:				https://v0lch0k.github.io/
disqus:             v0lch0k


